# Generated by Django 6.0 on 2025-12-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('Beginner/A1', 'Beginner/A1'), ('Elementary/A2', 'Elementary/A2'), ('Intermediate/B1', 'Intermediate/B1'), ('Upper-Intermediate/B2', 'Upper-Intermediate/B2'), ('Advanced/C1', 'Advanced/C1'), ('Proficient/C2', 'Proficient/C2')], max_length=30)),
                ('mentor', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
