# Generated by Django 6.0 on 2025-12-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
